class FarmGame{constructor(){this.c=gameConfig;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#b9dcf2');this.camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,500);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(devicePixelRatio);document.body.appendChild(this.renderer.domElement);this.clock=new THREE.Clock();this.keys={};this.move={x:0,z:0};this.player=null;this.people=[];this.animals=[];this.near=null;this.init()}
init(){this.scene.add(new THREE.HemisphereLight(0xffffff,0x668855,1.4));let sun=new THREE.DirectionalLight(0xffffff,1);sun.position.set(10,25,10);this.scene.add(sun);this.ground();this.playerBody();this.objects();this.touch();addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});this.loop()}
mat(c){return new THREE.MeshStandardMaterial({color:c})}ground(){let g=new THREE.Mesh(new THREE.PlaneGeometry(this.c.world.size,this.c.world.size),this.mat('#79b85d'));g.rotation.x=-Math.PI/2;this.scene.add(g);let road=new THREE.Mesh(new THREE.BoxGeometry(18,.04,4),this.mat('#d8bd83'));road.position.y=.02;this.scene.add(road)}
playerBody(){let g=new THREE.Group();let body=new THREE.Mesh(new THREE.CapsuleGeometry(.65,1.2,4,8),this.mat('#765645'));body.position.y=1.6;g.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.43,16,16),this.mat('#f0c5a2'));head.position.y=2.75;g.add(head);let legs=[];for(let x of [-.22,.22]){let l=new THREE.Mesh(new THREE.CapsuleGeometry(.17,.85,4,8),this.mat('#273044'));l.position.set(x,.48,0);g.add(l);legs.push(l)}g.position.y=0;this.player={mesh:g,legs,walk:0};this.scene.add(g)}
objects(){for(let [x,z] of this.c.world.trees){let t=new THREE.Mesh(new THREE.CylinderGeometry(.25,.35,2.2,8),this.mat('#74482e'));t.position.set(x,1.1,z);let l=new THREE.Mesh(new THREE.SphereGeometry(1.2,14,14),this.mat('#318344'));l.position.set(x,2.8,z);this.scene.add(t,l)}for(let [type,x,z] of this.c.world.animals)this.animal(type,x,z);for(let [name,x,z] of this.c.world.people)this.person(name,x,z)}
animal(type,x,z){let g=new THREE.Group(),color=type==='cow'?'#73482f':type==='sheep'?'#eee9df':'#e2c43f';let b=new THREE.Mesh(new THREE.BoxGeometry(1.2,.7,1.7),this.mat(color));b.position.y=.65;g.add(b);let h=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,.5),this.mat('#eed0ad'));h.position.x=.85;h.position.y=.85;g.add(h);g.position.set(x,0,z);g.userData={kind:'animal',name:type,traits:{hunger:Math.random()*40+50,happiness:70}};this.scene.add(g);this.animals.push(g)}
person(name,x,z){let g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.5,1,4,8),this.mat('#536bb3')),h=new THREE.Mesh(new THREE.SphereGeometry(.35,14,14),this.mat('#e6b995'));b.position.y=1.25;h.position.y=2.2;g.add(b,h);g.position.set(x,0,z);g.userData={kind:'person',name,traits:{curiosity:Math.round(Math.random()*100),happiness:Math.round(Math.random()*100),hunger:Math.round(Math.random()*100),temporaryMadness:Math.random()<.15}};this.scene.add(g);this.people.push(g)}
touch(){let bind=(id,x,z)=>{let b=document.getElementById(id),on=v=>this.move[v]=1,off=v=>this.move[v]=0;b.addEventListener('touchstart',e=>{e.preventDefault();on(x);on(z)}, {passive:false});b.addEventListener('touchend',e=>{e.preventDefault();off(x);off(z)}, {passive:false})};bind('up',0,-1);bind('down',0,1);bind('left',-1,0);bind('right',1,0)}
update(dt){let m=new THREE.Vector3(this.move.x,0,this.move.z);if(m.lengthSq()){m.normalize();this.player.mesh.position.addScaledVector(m,this.c.player.speed*dt);this.player.mesh.rotation.y=Math.atan2(m.x,m.z);this.player.walk+=dt*9}else this.player.walk+=dt*2;this.player.legs[0].rotation.x=Math.sin(this.player.walk)*.55;this.player.legs[1].rotation.x=-Math.sin(this.player.walk)*.55;let lim=this.c.world.size/2-2;this.player.mesh.position.x=THREE.MathUtils.clamp(this.player.mesh.position.x,-lim,lim);this.player.mesh.position.z=THREE.MathUtils.clamp(this.player.mesh.position.z,-lim,lim);this.people.forEach((p,i)=>{p.rotation.y+=Math.sin(performance.now()/1000+i)*dt*.2});this.findNear();this.follow()}
findNear(){let all=[...this.people,...this.animals],best=null,dist=3.2;for(let o of all){let d=o.position.distanceTo(this.player.mesh.position);if(d<dist){best=o;dist=d}}this.near=best;let prompt=document.getElementById('interactPrompt');prompt.classList.toggle('hidden',!best);if(best)document.getElementById('promptText').textContent=`Talk to ${best.userData.name}`}
follow(){let p=this.player.mesh.position,mode=this.c.camera.mode,d=new THREE.Vector3(p.x,mode==='topdown'?18:mode==='cinematic'?6:4,p.z+(mode==='topdown'?0:mode==='cinematic'?10:9));this.camera.position.lerp(d,.1);this.camera.lookAt(p.x,1.3,p.z)}setMode(m){this.c.camera.mode=m}interact(){if(!this.near)return;let u=this.near.userData;if(u.kind==='person')setStatus(`${u.name}: curiosity ${u.traits.curiosity}, happiness ${u.traits.happiness}, hunger ${u.traits.hunger}${u.traits.temporaryMadness?', feeling unpredictable':''}`);else setStatus(`Your ${u.name} is ${Math.round(u.traits.hunger)}% hungry and ${u.traits.happiness}% happy`)}shoot(){if(!this.c.camera.sound)return;let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=170;o.type='square';g.gain.setValueAtTime(.12,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.18);setStatus('Game action used: sound effect played')}
loop(){requestAnimationFrame(()=>this.loop());this.update(this.clock.getDelta());this.renderer.render(this.scene,this.camera)}}function setStatus(t){document.getElementById('status').textContent=t}