const state = { coins: gameConfig.player.coins, hunger: gameConfig.player.hunger, inventory: { ...gameConfig.player.inventory }, equipped: 'trainingBlaster' };
const game = new FarmGame();
const $ = id => document.getElementById(id);
function refresh() { $('coins').textContent = state.coins; $('hunger').textContent = state.hunger; $('itemCount').textContent = Object.values(state.inventory).reduce((a, b) => a + b, 0); $('inventoryList').innerHTML = Object.entries(state.inventory).map(([key, value]) => `<li class="itemRow"><span>${key}</span><b>${value}</b>${gameConfig.weapons[key] ? `<button data-equip="${key}">${state.equipped === key ? 'Equipped' : 'Equip'}</button>` : ''}</li>`).join('') || '<li>Empty</li>'; document.querySelectorAll('[data-equip]').forEach(button => button.onclick = () => { state.equipped = button.dataset.equip; refresh(); setStatus(`${gameConfig.weapons[state.equipped].name} equipped`); }); }
function panel(id) { $(id).classList.toggle('hidden'); }
function market() { const categories = [...new Set(gameConfig.market.map(item => item.category))]; $('marketTabs').innerHTML = categories.map(category => `<button data-cat="${category}">${category}</button>`).join(''); const draw = category => { $('marketList').innerHTML = gameConfig.market.filter(item => item.category === category).map(item => `<div class="marketCard"><span><b>${item.name}</b><small>${item.type}</small></span><button data-buy="${item.id}">${item.price} coins</button></div>`).join(''); document.querySelectorAll('[data-buy]').forEach(button => button.onclick = () => buy(button.dataset.buy)); }; document.querySelectorAll('[data-cat]').forEach(button => button.onclick = () => draw(button.dataset.cat)); draw(categories[0]); }
function buy(id) { const item = gameConfig.market.find(value => value.id === id); if (state.coins < item.price) { setStatus('Not enough coins'); return; } state.coins -= item.price; state.inventory[item.id] = (state.inventory[item.id] || 0) + 1; refresh(); setStatus(`${item.name} added to inventory`); }
function setStatus(text) { $('status').textContent = text; }
$('inventoryBtn').onclick = () => panel('inventoryPanel'); $('marketBtn').onclick = () => { panel('marketPanel'); market(); }; $('settingsBtn').onclick = () => panel('settingsPanel'); document.querySelectorAll('.close').forEach(button => button.onclick = () => button.parentElement.classList.add('hidden')); $('cameraSelect').onchange = event => game.setMode(event.target.value); $('soundToggle').onchange = event => game.c.camera.sound = event.target.checked; $('interactBtn').onclick = () => game.interact(); $('actionBtn').onclick = () => game.interact(); $('useBtn').onclick = () => game.useEquippedWeapon(state.equipped); refresh();
